sudo: required
services: 
  - docker

before_install:
  - docker build -t tajpuri/docker-react-cicd-boilerplate -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test