sudo: required
services: 
  - docker

before_install:
  - docker build -t ktajpuri/docker-react-cicd-boilerplate -f Dockerfile.dev .

script:
  - docker run -e CI=true ktajpuri/docker-react-cicd-boilerplate npm run test